
services:
  webapp:
    build: .
    command: python manage.py runserver melco2.cs.ualberta.ca:25500
    volumes:
      - .:/ana-demo
    env_file:
      - ./.env
    ports:
      - 25500:25500
    network_mode: host
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    network_mode: host
    ports:
     - 5432:5432
  
  redis:
    image: redis:7
    network_mode: host
    ports:
      - 6379:6379
  
  celery:
    build: .
    command: celery -A config worker -l info
    network_mode: host
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - webapp
    
volumes:
  postgres_data: