services:
  vllm-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vllm-container:latest
    shm_size: 1gb
    entrypoint: ["/bin/bash", "-c", "/workspace/vllm_serve.sh"]
    volumes:
      - deepseek_model:/models/DeepSeek:ro
    gpus: "all"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1
    env_file:
      - ./.env
    ports:
      - "25601:25601"


  vllm-embed:
    build:
      context: .
      dockerfile: Dockerfile
    image: vllm-container:latest
    entrypoint: ["/bin/bash", "-c", "/workspace/vllm_embedding.sh"]
    volumes:
      - e5_model:/models/e5-large-v2:ro
    gpus: "all"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    env_file:
      - ./.env
    ports:
      - "25602:25602"

volumes:
  deepseek_model:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Desktop/LMs/DeepSeek-R1-14B
      o: bind
  e5_model:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/Desktop/LMs/e5-large-v2
      o: bind
