# Generated by Django 5.0.4 on 2025-07-23 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("bot", "bot"), ("user", "user")], max_length=5
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("joke", "joke"),
                            ("read book", "read book"),
                            ("story", "story"),
                            ("phone", "phone"),
                            ("weather", "weather"),
                            ("other", "other"),
                        ],
                        default="other",
                        max_length=64,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
